### ISSUE TITLE
URL issue with scraping of COSEM data

### ISSUE THREAD

**Issue by federico-carrara** [tlambert03/microsim#64]
### Description

A colleague and I spotted an error while loading COSEM data from the web. 
We believe the URL [here](https://github.com/tlambert03/microsim/blob/main/src/microsim/cosem/_client.py#L67) is no longer valid.  

### What I Did

By replacing the old link with this: https://openorganelle.janelia.org/static/js/8591.066f2952.chunk.js, we temporarily fixed the problem. However, we wonder if this issue will happen again in the future and, therefore, if a more robust fix is needed.

**Comment by tlambert03** [comment]
ah darn... yeah, that was a hack... will discuss offline

**Comment by tlambert03** [comment]
fixed in #65 and released in v0.0.5
