### ISSUE TITLE
Unit of measure of Spectrum intensity

### ISSUE THREAD

**Issue by federico-carrara** [tlambert03/microsim#70]
### Description

I found some inconsistency in typing the `Spectrum.intensity` attribute.

Indeed, while in the `Spectrum` [model](https://github.com/tlambert03/microsim/blob/main/src/microsim/schema/spectrum.py#L30) it is defined as a `NumpyNdarray` without unit of measure, in the [`get_excitation_rate()` function](https://github.com/tlambert03/microsim/blob/main/src/microsim/schema/_emission.py#L75) a unit of measure is appended to it.

Now, the problem is that functions that operate on `Spectrum` objects would need different ways to access the `intensity` values (specifically, `spectrum.intensity` or `spectrum.intensity.magnitude`). 

### Possible fix
I see at least a couple of options:

- Temporarily use an `if isinstance(...)` statement where is needed in the functions that use `intensity`.
- Change typing of `Spectrum.intensity` to include unit of measure from the beginning.

**Comment by tlambert03** [comment]
yeah, typing that one is tricky.

I'm waffling here a bit on whether it's a good idea to use pint in pydantic models at all. so, while option number 2 would be the most consistent with the other models (and consistency is good) i feel like it's going deeper into a questionable pattern.  and, some spectra relative/normalized spectra) *should* be allowed not to have units... though pint can definitely support that with "dimensionless" quantities.

> Temporarily use an if isinstance(...)

i guess that's the ugly/best approach here
